### ISSUE TITLE
CAT_STATEMENT_TABLE_FULL during ichksum

### ISSUE THREAD

**Issue by anderbubble** [irods/irods#4732]
- [x] master
- [x] 4-2-stable
------

### iRODS Version, OS and Version

```
$ rpm -q irods-server
irods-server-4.2.7-1.x86_64

$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
```

### What did you try to do?

```
$ sudo -u irods ichksum -MaK --verify -vr "/civilfritz.net/home/janderson/games"
```

### Expected behavior

Successful ichksum of all files under `/civilfritz.net/home/janderson/games`, like

```
    BRAIN.NFO    sha2:V+5dNdmpltyFekNXLA0JyLi8LIoKMVYtIz5nUDTIFqg=
   BRAIN.NFO                  0.039 sec
```

### Observed behavior (including steps to reproduce, if applicable)

```
remote addresses: 128.138.138.142 ERROR: chksumDataObjUtil: rcDataObjChksum error for /civilfritz.net/home/janderson/games/castle/drbrain/BRAINSG.000 status = -860000 CAT_STATEMENT_TABLE_FULL
remote addresses: 128.138.138.142 ERROR: chksumCollUtil:chksumDataObjU failed for /civilfritz.net/home/janderson/games/castle/drbrain/BRAINSG.000.stat = -860000 status = -860000 CAT_STATEMENT_TABLE_FULL
```

**Comment by d-w-moore** [comment]
@anderbubble  -  So far I haven't been able to reproduce this on a vanilla Centos 7.7 setup. Can you share any additional system details? Is this a single-node system? Have any rules been configured which would trigger on opening or reading data objects?

**Comment by anderbubble** [comment]
@d-w-moore it's a single-node system, yes. I had an early version of the logical quotas stuff enabled at one point, but I think it's all torn out now (and I definitely removed all the relevant imeta).

I'm happy to share my config; just let me know what you want to see.

**Comment by d-w-moore** [comment]
@anderbubble  Still working through the simpler possibilities at the moment. Perhaps you could send an 'ilsresc -l' output and a rough idea of the object hierarchy itself -- a listing of the output of "ils -lr /civilfritz.net/home/janderson/games" if it's not confidential, or too large.

**Comment by anderbubble** [comment]
```
[janderson@fox1 ~]$ ilsresc
rootResc:passthru
└── replResc:replication
    ├── fox1Resc:unixfilesystem
    ├── mybook:unixfilesystem
    └── rsync_net:unixfilesystem
www:passthru
└── ln1:unixfilesystem
```

`ils -lr /civilfritz.net/home/janderson/games` is 16037 entries long, and I'd rather not post it here; but I'm happy to share it out-of-band if you can give me a place to send it. (@trel has my email address)

**Comment by d-w-moore** [comment]
It's good enough for now, I will see about reproducing it using an identical replication resource with three leaf nodes. Thanks!

**Comment by d-w-moore** [comment]
Haven't been able to reproduce. Maybe send any native and/or Python rule bases that might be relevant, and an ils -lr of the root collection involved to support@irods.org

**Comment by trel** [comment]
After a call today, we were able to reproduce the leaking statements with `ichksum -r -K --verify` on a collection with 50+ total replicas (either single replica data objects, or in duplicate/triplicate).

This branch of the code needs to call `rsGenQuery` properly, and clean up after itself.

**Comment by trel** [comment]
Interestingly, without the admin flag (`-M`), I get `CAT_NO_ACCESS_PERMISSION`:
```bash
ichksum -rK --verify ichksumtest
```

Adding the `-M` flag gives the `CAT_STATEMENT_TABLE_FULL` error instead:

```bash
ichksum -MrK --verify ichksumtest
```

Both are a problem and should be fixed...

However, the `CAT_NO_ACCESS_PERMISSION` error is also concerning since all these files belong to me.

**Comment by d-w-moore** [comment]
I see the same. probably all stems from the common cause of not freeing the thing, is my guess, but we'll see...

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by anderbubble** [comment]
@trel and @d-w-moore be advised, I tried this same operation again on my (newly reinstalled) test system on the same dataset using irods 4.2.8. The error message has changed, and I think it's occurring slightly later in the dataset; but it's still failing. First error message included below.

```
[janderson@fox1 ~]$ rpm -qa | grep irods
irods-externals-clang-runtime6.0-0-1.0-1.x86_64
irods-externals-fmt6.1.2-1-1.0-1.x86_64
irods-icommands-4.2.8-1.x86_64
irods-externals-nanodbc2.13.0-0-1.0-1.x86_64
irods-externals-zeromq4-14.1.6-0-1.0-1.x86_64
irods-runtime-4.2.8-1.x86_64
irods-externals-avro1.9.0-0-1.0-1.x86_64
irods-externals-libarchive3.3.2-1-1.0-1.x86_64
irods-database-plugin-postgres-4.2.8-1.x86_64
irods-externals-catch22.3.0-0-1.0-1.x86_64
irods-server-4.2.8-1.x86_64
irods-externals-boost1.67.0-0-1.0-1.x86_64
irods-externals-json3.7.3-0-1.0-1.x86_64
```

```
remote addresses: 128.138.138.142 ERROR: chksumDataObjUtil: rcDataObjChksum error for /civilfritz.net/home/janderson/games/Atari 2600/ROM/Beat 'Em and Eat 'Em (1982) (Mystique) [!].bin status = -154000 SYS_INTERNAL_ERR
remote addresses: 128.138.138.142 ERROR: chksumCollUtil:chksumDataObjU failed for /civilfritz.net/home/janderson/games/Atari 2600/ROM/Beat 'Em and Eat 'Em (1982) (Mystique) [!].bin.stat = -154000 status = -154000 SYS_INTERNAL_ERR
 ERROR: [-]	/irods_git_repo/lib/core/src/procApiRequest.cpp:182:int sendApiRequest(rcComm_t *, int, void *, bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
	[-]	/irods_git_repo/lib/core/src/sockComm.cpp:1257:irods::error sendRodsMsg(irods::network_object_ptr, const char *, bytesBuf_t *, bytesBuf_t *, bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [failed to call 'write body']
		[-]	/irods_git_repo/plugins/network/tcp/libtcp.cpp:355:irods::error tcp_send_rods_msg(irods::plugin_context &, const char *, bytesBuf_t *, bytesBuf_t *, bytesBuf_t *, int, irodsProt_t) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [writeMsgHeader failed]
			[-]	/irods_git_repo/lib/core/src/sockComm.cpp:475:irods::error writeMsgHeader(irods::network_object_ptr, msgHeader_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 141]
				[-]	/irods_git_repo/plugins/network/tcp/libtcp.cpp:293:irods::error tcp_write_msg_header(irods::plugin_context &, bytesBuf_t *) :  status [SYS_HEADER_WRITE_LEN_ERR]  errno [Broken pipe] -- message [wrote 0 expected 141]
```

**Comment by d-w-moore** [comment]
@anderbubble Is it and deterministic? How many other objects are within the same collection as the failing object -- and, if you start the ichksum at a lower point in the tree, is the exact same object flagged with the checksum error?

**Comment by anderbubble** [comment]
@d-w-moore 

> Is it reproducible / deterministic

Yes, so far. It appears to be failing reliably at `/civilfritz.net/home/janderson/games/Atari 2600/ROM/Beat 'Em and Eat 'Em (1982) (Mystique) [!].bin`.

> How many other objects are within the same collection as the failing object

Looks like 517. The first failure is at object 37 in the order reported by `ils`. (And, to be clear, _all_ objects fail after that.)

> if you start the ichksum at a lower point in the tree, is the exact same object flagged with the checksum error

Yes; if I run the command against `/civilfritz.net/home/janderson/games/Atari 2600/ROM` it fails at the same point.

This time I checked `rodsLog`, too:

```
terminating with uncaught exception of type irods::exception: iRODS Exception:
    file: /irods_git_repo/lib/core/include/irods_query.hpp
    function: irods::query<rsComm_t>::gen_query_impl::gen_query_impl(connection_type *, int, int, const std::string &, const std::string &) [connection_type = rsComm_t]
    line: 202
    code: -1107000 (NO_COLUMN_NAME_FOUND)
    message:
        query fill failed for [select DATA_SIZE where DATA_PATH = '/media/rsync.net/Vault/home/janderson/games/Atari 2600/ROM/Beat 'Em and Eat 'Em (1982) (Mystique) [!].bin']
stack trace:
--------------

Dumping stack trace
<0>	Offset: 0x6e  	Address: 0x7f28d43886be	irods::exception::exception(long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<1>	Offset: 0x42  	Address: 0x7f28d4388882	irods::exception::exception(long, boost::basic_format<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<2>	Offset: 0x22d 	Address: 0x7f28d715369d	irods::query<rsComm_t>::gen_query_impl::gen_query_impl(rsComm_t*, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<3>	Offset: 0x98  	Address: 0x7f28d7152d88	irods::query<rsComm_t>::query(rsComm_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, irods::query<rsComm_t>::query_type)
<4>	Offset:       	Address: 0x7f28d71517ff	/lib/libirods_server.so.4.2.8(+0x9ca7ff) [0x7f28d71517ff]
<5>	Offset: 0x427 	Address: 0x7f28d7150e17	_rsDataObjChksum(rsComm_t*, DataObjInp*, char**, DataObjInfo**)
<6>	Offset: 0x428 	Address: 0x7f28d7150838	rsDataObjChksum(rsComm_t*, DataObjInp*, char**)
<7>	Offset: 0x52  	Address: 0x7f28d73faf22	irods::api_call_adaptor<DataObjInp*, char**>::operator()(irods::plugin_context&, rsComm_t*, DataObjInp*, char**)
<8>	Offset: 0x16  	Address: 0x7f28d73fae96	std::__1::__function::__func<irods::api_call_adaptor<DataObjInp*, char**>, std::__1::allocator<irods::api_call_adaptor<DataObjInp*, char**> >, irods::error (irods::plugin_context&, rsComm_t*, DataObjInp*, char**)>::operator()(irods::plugin_context&, rsComm_t*&&, DataObjInp*&&, char**&&)
<9>	Offset: 0xcb6 	Address: 0x7f28d72c78f6	int irods::api_entry::call_handler<DataObjInp*, char**>(rsComm_t*, DataObjInp*, char**)
<10>	Offset: 0x70d 	Address: 0x7f28d751e55d	rsApiHandler(rsComm_t*, int, BytesBuf*, BytesBuf*)
<11>	Offset: 0xa4b 	Address: 0x7f28d752062b	readAndProcClientMsg(rsComm_t*, int)
<12>	Offset: 0xd08 	Address: 0x7f28d7511548	agentMain(rsComm_t*)
<13>	Offset: 0x1fa5	Address: 0x7f28d750f795	runIrodsAgentFactory(sockaddr_un)
<14>	Offset:       	Address: 0x426ffd	/usr/sbin/irodsServer(main+0x4cd) [0x426ffd]
<15>	Offset:       	Address: 0x7f28d385a555	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f28d385a555]
<16>	Offset:       	Address: 0x426a67	/usr/sbin/irodsServer() [0x426a67]



Caught signal [6]. Dumping stacktrace and exiting

Dumping stack trace
<0>	Offset:       	Address: 0x7f28d74ebf33	/lib/libirods_server.so.4.2.8(+0xd64f33) [0x7f28d74ebf33]
<1>	Offset:       	Address: 0x7f28d3c15630	/lib64/libpthread.so.0(+0xf630) [0x7f28d3c15630]
<2>	Offset:       	Address: 0x7f28d386e387	/lib64/libc.so.6(gsignal+0x37) [0x7f28d386e387]
<3>	Offset:       	Address: 0x7f28d386fa78	/lib64/libc.so.6(abort+0x148) [0x7f28d386fa78]
<4>	Offset:       	Address: 0x7f28d7fbc8fc	/opt/irods-externals/clang-runtime6.0-0/lib/libc++abi.so.1(+0x1c8fc) [0x7f28d7fbc8fc]
<5>	Offset:       	Address: 0x7f28d7fac563	/opt/irods-externals/clang-runtime6.0-0/lib/libc++abi.so.1(+0xc563) [0x7f28d7fac563]
<6>	Offset:       	Address: 0x7f28d7fbbd76	/opt/irods-externals/clang-runtime6.0-0/lib/libc++abi.so.1(+0x1bd76) [0x7f28d7fbbd76]
<7>	Offset:       	Address: 0x7f28d7fbebb7	/opt/irods-externals/clang-runtime6.0-0/lib/libc++abi.so.1(+0x1ebb7) [0x7f28d7fbebb7]
<8>	Offset: 0x248 	Address: 0x7f28d71536b8	irods::query<rsComm_t>::gen_query_impl::gen_query_impl(rsComm_t*, int, int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
<9>	Offset: 0x98  	Address: 0x7f28d7152d88	irods::query<rsComm_t>::query(rsComm_t*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long, irods::query<rsComm_t>::query_type)
<10>	Offset:       	Address: 0x7f28d71517ff	/lib/libirods_server.so.4.2.8(+0x9ca7ff) [0x7f28d71517ff]
<11>	Offset: 0x427 	Address: 0x7f28d7150e17	_rsDataObjChksum(rsComm_t*, DataObjInp*, char**, DataObjInfo**)
<12>	Offset: 0x428 	Address: 0x7f28d7150838	rsDataObjChksum(rsComm_t*, DataObjInp*, char**)
<13>	Offset: 0x52  	Address: 0x7f28d73faf22	irods::api_call_adaptor<DataObjInp*, char**>::operator()(irods::plugin_context&, rsComm_t*, DataObjInp*, char**)
<14>	Offset: 0x16  	Address: 0x7f28d73fae96	std::__1::__function::__func<irods::api_call_adaptor<DataObjInp*, char**>, std::__1::allocator<irods::api_call_adaptor<DataObjInp*, char**> >, irods::error (irods::plugin_context&, rsComm_t*, DataObjInp*, char**)>::operator()(irods::plugin_context&, rsComm_t*&&, DataObjInp*&&, char**&&)
<15>	Offset: 0xcb6 	Address: 0x7f28d72c78f6	int irods::api_entry::call_handler<DataObjInp*, char**>(rsComm_t*, DataObjInp*, char**)
<16>	Offset: 0x70d 	Address: 0x7f28d751e55d	rsApiHandler(rsComm_t*, int, BytesBuf*, BytesBuf*)
<17>	Offset: 0xa4b 	Address: 0x7f28d752062b	readAndProcClientMsg(rsComm_t*, int)
<18>	Offset: 0xd08 	Address: 0x7f28d7511548	agentMain(rsComm_t*)
<19>	Offset: 0x1fa5	Address: 0x7f28d750f795	runIrodsAgentFactory(sockaddr_un)
<20>	Offset:       	Address: 0x426ffd	/usr/sbin/irodsServer(main+0x4cd) [0x426ffd]
<21>	Offset:       	Address: 0x7f28d385a555	/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f28d385a555]
<22>	Offset:       	Address: 0x426a67	/usr/sbin/irodsServer() [0x426a67]

Jun 22 21:56:26 pid:2388  ERROR: Agent process [7791] exited with status [6]
```

**Comment by trel** [comment]
This appears to be a string parsing error - the single quotes in the filename are messing with the GenQuery.   Please open a new issue for this, @d-w-moore.

```
        query fill failed for [select DATA_SIZE where DATA_PATH = '/media/rsync.net/Vault/home/janderson/games/Atari 2600/ROM/Beat 'Em and Eat 'Em (1982) (Mystique) [!].bin']
```

**Comment by trel** [comment]
Okay, it's a new issue - keeping this one closed... https://github.com/irods/irods/issues/4983
